name: Update-Warrants
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install requests beautifulsoup4 pytz
      - name: Run
        run: python crawler.py
      - name: Deploy
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Auto Update" || exit 0
          git push
